### ISSUE TITLE
Expose ability to set HTTP/HTTPS in Agent

### ISSUE THREAD

**Issue by geoghegan** [matisku/bamboo-docker#10]
Currently the only transport protocol supported during install is HTTP.

The user should be able to define what transport protocol to use - e.g. HTTPS or HTTP.

**Comment by geoghegan** [comment]
Actually, this might not be needed. Thoughts,  @matisku ?

**Comment by matisku** [comment]
It all depends on a setup. Might me needed as a option.

**Comment by geoghegan** [comment]
I tried connecting over HTTP to a HTTPS bamboo server to pull down the JAR file - appears to work, although my setup uses a 301 redirect from HTTP to HTTPS that only changes the protocol.

I imagine most people would also be using a 301 redirect that only changes the protocol as well.

**Comment by geoghegan** [comment]
I don't think this is actually needed any more
