### ISSUE TITLE
Support for Agent security token verification

### ISSUE THREAD

**Issue by geoghegan** [matisku/bamboo-docker#5]
Bamboo supports "Security Token Verification" - where the agent passes a, static, token to the server for authentication. 

It would be nice for the agent scripts to support these security tokens.

The format for launching with a security token is 
```
java -jar atlassian-bamboo-agent-installer-${AGENT_VERSION}.jar http://${BAMBOO_SERVER}:${BAMBOO_SERVER_PORT}/agentServer/ -t ${BAMBOO_SECURITY_TOKEN}
```

**Comment by geoghegan** [comment]
`-e BAMBOO_SECURITY_TOKEN=foobarbaz` should be used to invoke this security token environmental variable  on the command line.

**Comment by matisku** [comment]
Looks like a good idea. Did you tested it?

**Comment by geoghegan** [comment]
Yes, on my laptop and an AWS box both running Docker. Works fine

**Comment by appkr** [comment]
What's this? Did I do something wrong in the forked version? Really sorry for the 4 consecutive messages. **EDIT** I get the reason, which was wrong rebase in my forked branch. No effect on the main code base, though, Sorry again.

**Comment by geoghegan** [comment]
Yeah, I'm not too sure what happened! :-D
