### ISSUE TITLE
Support for custom agent homedir

### ISSUE THREAD

**Issue by geoghegan** [matisku/bamboo-docker#9]
The agent should support arbitrary `BAMBOO_AGENT_HOME` directories passed in as an environmental variable. 

Currently the `BAMBOO_AGENT_HOME` defaults to `/root/`. With an arbitrary homedir, we can mount this from the Docker host and preform actions on it outside the container

**Comment by geoghegan** [comment]
In Docker, use `-e BAMBOO_HOME="/opt/bamboo"` to use this feature

**Comment by matisku** [comment]
This is a good point. Home Dir: `/opt/bamboo` is definitely better than `/root` :)

**Comment by geoghegan** [comment]
Any chance of getting this accepted into mainline? PR inbound :-)

**Comment by geoghegan** [comment]
Thanks!
